### ISSUE TITLE
Crash if used in recyclerview.

### ISSUE THREAD

**Issue by vishaliiita** [Meetic/Shuffle#18]
I have used Shuffle inside a recyclerview. App crashes when user trying to drag card. It is easy to repro.
1. Add few elements in recyclerview. Keep one of them as Shuffle layout.
2. Scroll to make Shuffle view inside view port.
3. scroll back to make shuffle outside of view port.
4 Scroll again to make same shuffle view inside view port again.
5. Now try to drag a view.

App crashes with following stack.

`11-12 15:11:27.558 10126-10126/com.fabulyst.mobile E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.fabulyst.mobile, PID: 10126
                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setScaleX(float)' on a null object reference
                                                                         at android.support.v4.view.ViewCompatHC.setScaleX(ViewCompatHC.java:126)
                                                                         at android.support.v4.view.ViewCompat$HCViewCompatImpl.setScaleX(ViewCompat.java:1177)
                                                                         at android.support.v4.view.ViewCompat.setScaleX(ViewCompat.java:2613)
                                                                         at com.meetic.shuffle.ShuffleViewAnimator.updateViewsPositions(ShuffleViewAnimator.java:323)
                                                                         at com.meetic.shuffle.Shuffle$3.onDrag(Shuffle.java:339)
                                                                         at com.meetic.dragueur.DraggableView.update(DraggableView.java:245)
                                                                         at com.meetic.dragueur.DraggableView.update(DraggableView.java:236)
                                                                         at com.meetic.dragueur.DraggableView.handleTouch(DraggableView.java:344)
                                                                         at com.meetic.dragueur.DraggableView.onTouchEvent(DraggableView.java:230)
                                                                         at android.view.View.dispatchTouchEvent(View.java:9300)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
                                                                         at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                         at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                         at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
                                                                         at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                         at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                         at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                         at android.view.View.dispatchPointerEvent(View.java:9520)
                                                                         at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                         at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                     	at android`

**Comment by vishaliiita** [comment]
In ShuffleViewAnimator.java, shuffle.getDraggableView(i) returning null.
